name: Java Junit Testing

on:
  push:
    branches: ["lab01"]
  pull_request:
    branches: ["lab01"]
  
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Compile Java code
        run: |
          $files = Get-ChildItem -Recurse lab01 -Filter *.java | ForEach-Object FullName
          javac -d out -cp "lib/junit-platform-console-standalone-1.13.0-M3.jar" $files
        shell: powershell

      - name: Run JUnit tests
        run: |
          java -jar lib/junit-platform-console-standalone-1.13.0-M3.jar \
            --class-path out \
            --scan-class-path